DROP DATABASE IF EXISTS QuanLySinhVien;
CREATE DATABASE QuanLySinhVien;
USE QuanLySinhVien;
CREATE TABLE Class(
ClassID 	INT AUTO_INCREMENT PRIMARY KEY ,
ClassName	VARCHAR(60) NOT NULL,
StartDate 	DATETIME NOT NULL,
`Status`	BIT
);

CREATE TABLE Student(
StudentID 	INT AUTO_INCREMENT PRIMARY KEY ,
StudentName VARCHAR(30) NOT NULL,
Address 	VARCHAR(50),
Phone		VARCHAR(20),
`Status` 	BIT,
`ClassId` 	INT NOT NULL
);

CREATE TABLE `Subject`(
SubID 		INT AUTO_INCREMENT PRIMARY KEY ,
SubName 	VARCHAR(30) NOT NULL,
Credit 		TINYINT NOT NULL DEFAULT 1 CHECK (Credit >=1),
`Status` 	BIT DEFAULT 1
);

CREATE TABLE Mark(
MarkID 		INT AUTO_INCREMENT PRIMARY KEY ,
SubID 		INT NOT NULL,
StudentID 	INT NOT NULL,
Mark 		FLOAT DEFAULT 1 CHECK (Mark BETWEEN 0 AND 100),
ExameTimes 	TINYINT NOT NULL DEFAULT 1,
UNIQUE (SubID, StudentID),
FOREIGN KEY (SubID) REFERENCES `Subject` (SubID),
FOREIGN KEY (StudentID) REFERENCES `Student` (StudentID)
);
